### PR TITLE
CRUD for Data Explorer Queries and Views

### PR DESCRIPTION
**Pull request by josvr**
In this branch we launch CRUD for Data Explorer.

### CODE REVIEW

**Comment by cskeefer** [comment]
Wow this look like a lot of work! I was just going to give it a try but seem to be running into some issues when going to the List of Queries page. It seems like you might be using MarkLogic 9? I'm using 8 and I'm seeing issues like:
* XDMP-EXTENSION: (err:XPST0003) MarkLogic extension syntax used, XQuery 3.1 apply to operators are not supported in 1.0-ml mode in /server/endpoints/api-crud-list-queries.xqy, at 15:32 [1.0-ml]
* XDMP-UNDFUN: (err:XPST0017) Undefined function map:with() in /server/endpoints/api-crud-list-queries.xqy, at 16:24, in local:get-queries() [1.0-ml]

**Comment by josvr** [comment]
I withdraw this pull request, to implement #94 and #44 in branch FERR-90

**Comment by josvr** [comment]
I have reopened this pull request. Great new features included. See my mail

**Comment by markschiffner** [comment]
Damon and I have discussed how to best address the pull request.
Nick did initial testing and this pull request fixes the findings and adds additional updates.
We decided to move forward and merge the pull request now without waiting for another full test.
Everyone on the team should do a full application test like we did for the beta release

**Pull request merged**
