### PR TITLE
135 - Duplicate fields break search

### PR DESCRIPTION
**Pull request by nlaprell**
Validate query/view selected fields and return an error containing a list of any duplicate field names.

### CODE REVIEW

**Comment by cskeefer** [comment]
When making a query, if I leave more than 1 filed set to No (so not in query) then I receive an error message like:

image

Looks like it is because $scope.wizardForm.fields[i-1].title is undefined if the user hasn't selected an include mode so undefined is getting added to dups. We should probably only check the title if the includeMode is not none?

**Comment by cskeefer** [comment]
Sorry, got click-crazy and click closed on accident

**Comment by nlaprell** [comment]
@cskeefer - Great catch. I fixed it to prevent processing fields that aren't included in the last commit.

**Comment by cskeefer** [comment]
@nlaprell looks good but I did notice a side effect of the fix when testing. To recreate do the following:

- Add a new query and only include only 2 fields (basically just need to include fewer fields than are available and include mode doesn't matter, can be Both, Search Field only, or Results Field only)
- Next, in Edit Config, click Display Views for your new query
- Click Create a View
- Confirm that only the two fields you included in your query are available in the view creation rather than all fields

It seems like, when creating a query, the backend expects all fields to be passed to it (regardless of if the field is to be included in the search, display, or both). But now it looks like we're just passing the fields that have an includeMode != none. Maybe just use the new includeMode test for dups rather than for also determining what fields get sent to the backend?

**Comment by nlaprell** [comment]
@cskeefer - Yeah, looks like I was skipping past setting the fields in the loop if it wasn't included, when I should have just wrapped the dupe logic. Fixed in the last commit. Thanks!

**Pull request merged**
