### PR TITLE
Automatic Version Update

### PR DESCRIPTION
**Pull request by nlaprell**
version.js file at the root contains the application version number. It is deployed to the client assets folder both via mlDeploy and when deploying with a .jar. The main controller references the data in version.js to render the version number in the application footer.

### CODE REVIEW

**Comment by nlaprell** [comment]
@cskeefer good point. I added the file to the project root for visibility, but I'm not opposed to moving it. I have updated .gitignore so it doesn't get checked it.

**Comment by cskeefer** [comment]
I like the visibility of it at the root also. I think I messed you up with my previous comment. I mistakenly called the file version.json rather than version.js so it looks like you added the gitignore for version.json. Sorry about that. If you can fix that I think it's all good.

**Comment by nlaprell** [comment]
@cskeefer - Great catch. I updated the file.
@markschiffner  - Do we have a versioning convention yet? A standard I've seen is x.y.z where x is incremented by 1 for each major public release, y is incremented between major releases, and z is incremented for each commit to y. If we adapt something similar, I've read that we can update git commit triggers to automatically increment z in the version.js file, thought I haven't tried this myself yet.

**Comment by cskeefer** [comment]
@nlaprell - .gitignore change looks good. I'm good with your versioning convention.

Are we leaving this open until we figure out the version we're working towards and convention? We could close this out and put any of that work in another "versioning convention" ticket. If no one response today otherwise I'll merge this.

**Comment by nlaprell** [comment]
@cskeefer - The version in this branch is 0.2.0, which I believe is what we are displaying in the current Master branch, so it should be good to go. We'll want to update it based on whatever naming convention we decide on before making a new build, but that doesn't need to happen here.

**Comment by cskeefer** [comment]
@nlaprell Sounds good to me.

**Pull request merged**
